// The print num *2
 public class extrastudy 
 {
  public static void main(String args[]) {
     int num; // this declares a variable called num
      num = 100; // this assigns num the value 100
      System.out.println("This is num: " + num);
      num = num * 2;
      System.out.println("The value of num * 2 is ");
     System.out.println(num);
}
}

// ln is used to print next line 



/*
Demonstrate the if.
Call this file "IfSample.java".
*/
class IfSample 
{
   public static void main(String args[]) {
   int x, y;
    x = 10;
    y = 20;
     if(x < y)
	 {
		 System.out.println("x is less than y");
	 }
     x = x * 2;
    if(x == y)
	{
		System.out.println("x now equal to y");
	}
    x = x * 2;
   if(x > y) 
   {
	   System.out.println("x now greater than y");
   } 
   // this won't display anything
   if(x == y) System.out.println("you won't see this");
   }
  }
/*The output generated by this program is shown here:
x is less than y
x now equal to y
x now greater than y
*/


class forloop11
{
	   public static void main(String args[]) {
		   
		   for(int x = 1; x <= 10; x++)
		   {
			   System.out.println("the no is "+ x);
		   }
	   }
}






class block
{
	public static void main(String args[])
	{
		int x,y;
		y = 20;
		   for( x = 0; x <= 10; x++)
		   {
			   System.out.println("This is the x:" + x);
			   System.out.println("This is the y:" + y);
			   y = y - 2;
			   
		   }
	}
}



/*
this will generate output 


*/